### ISSUE TITLE
Priorities being wonky with Revive of the Fluffies work tab mod.

### ISSUE THREAD

**Issue by CaptainBartPeterson** [Lauriichan/PriorityMaster#3]
### RimWorld version

1.5

### Other mod name

Work Tab - 1.5 Unofficial by DomB

### Mod list

Rimpy Modlist from Google Drive:
https://drive.google.com/file/d/19mjwgwUeIJ4aDqbPxFj_7qevHd9SWfl8/view?usp=sharing

### Describe what happend

When I set priorities to anything above 9, upon load the priority will be set as if game was confused and thought instead of for example 10 it should put Hour 1: P1 Hour 2: P9 and so forth repeating. ( It dosen't appear on the Visual exception load bug rundown and I can't spot in the log.) It appears to be a cosmetic display but I'm not sure, as pawns didn't seam to act wierdly.

### Reproduction steps

1. In game set priority above 9 2. Save/Load Game 3. Priorites get fucky.

### Expected behavior

It happens on load/save as far as I can tell.

### Additional Information

Modlist is mostly optimized but it's not perfect it may be something to do with another mod and Work Tab is just displaying it wierd, unfortunatly It dosen't leave info in the log, as far as I can tell.

**Comment by Lauriichan** [comment]
After some investigation it turns out that Fluffy was never actually fully compatible with Priority Master.
The "per-hour priority" feature saves priorities in a single digit format which makes no sense with Priority Master installed.

**Comment by Lauriichan** [comment]
The new version will be available on steam soon
